[general]
import = [
    "~/.config/alacritty/hl2.toml"   # HL2; vorher themes/themes/autumn.toml
]

[font]
size=9


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[[keyboard.bindings]]
key = "Back"
chars = "\u0008"
